site_name: Durango Retro Computer
site_description: Home of the Durango Computer Project. Create a 8 bit home computer with modern tools.
site_author: Durango Computer Team
nav:
 - Home: index.md
 - About: about.md
 - Getting Started: started.md
 - FAQ: faq.md
 - The Hardware: 
    - Hardware: hardware/hardware.md
    - Durango: hardware/durango.md
    - KeyBoard: hardware/keyboard.md
    - Cartridge: hardware/cartidge.md
    - Development Cartridge: hardware/dev_cart.md
 - The Software:
    - Software: software/software.md
    - Games: software/games.md
    - Roms: software/roms.md
 - Troubleshoot: troubleshoot.md
 - Development & Tools:
    - Development: tools/development.md
    - Tools: tools/tools.md
    - Emulator (Perdita): tools/perdita.md
    - Durango Lib: tools/durangolib.md
    - Docker: tools/docker.md
    - Durango Code: tools/durangocode.md
 - Other Projects:
    - Other Projects: other/other.md
    - Future Projects: other/future.md
    - Abandoned Projects: other/abandoned.md
 - Community: community.md
 - Contribute: https://github.com/durangoretro/
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/durangoretro/
  generator: false
copyright: Copyright &copy; 2020 - 2023 Durango Computer Team
repo_name: durangoretro/web
repo_url: https://github.com/durangoretro/web
theme:
  name: material
  custom_dir: theme
  nav_style: dark
  features:
    - navigation.tabs
  logo: assets/img/logo.png
  favicon: assets/img/favicon.png
  palette:
    scheme: slate
    accent: blue
    primary: purple
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.superfences
  - tables
